# Preparação dos Dados

### Importação das Bibliotecas

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings
warnings.filterwarnings('ignore')

import plotly.graph_objects as go
import plotly.express as px

# plot parameters
%matplotlib inline
plt.rcParams['font.size'] = 14
plt.rcParams['figure.figsize'] = (9, 5)
plt.rcParams['figure.facecolor'] = '#00000000'

### Leitura dos Dados

In [2]:
df = pd.read_csv("data/dados.csv")
df_base = df

In [3]:
df.head()

Order_ID Order_Priority  Order_Quantity    Sales    Ship_Mode  Profit  \
0       643           High              21  2781.82  Express Air -695.26   
1      8995           High              35  3389.93  Express Air  737.94   
2      9127  Not Specified               7  2039.56  Express Air -329.49   
3     26272            Low               6   905.94  Express Air   -4.19   
4     36646         Medium              24  1168.15  Express Air -743.96   

        Customer_Name                 Region Customer_Segment  \
0      Monica Federle                Nunavut        Corporate   
1          Beth Paige  Northwest Territories         Consumer   
2         Bryan Davis  Northwest Territories        Corporate   
3         Carlos Daly  Northwest Territories      Home Office   
4  Muhammed MacIntyre  Northwest Territories   Small Business   

  Product_Category    Product_Sub-Category  \
0  Office Supplies  Storage & Organization   
1        Furniture      Office Furnishings   
2  Office Supplies  Storage & Organization   
3        Furniture      Chairs & Chairmats   
4  Office Supplies  Storage & Organization   

                                        Product_Name Product_Container  
0              SAFCO Commercial Wire Shelving, Black         Large Box  
1       Luxo Professional Combination Clamp-On Lamps         Large Box  
2  Tennsco Snap-Together Open Shelving Units, Sta...         Large Box  
3                           Hon Olson Stacker Stools         Large Box  
4                        Tennsco Industrial Shelving         Large Box

In [4]:
df.columns

Index(['Order_ID', 'Order_Priority', 'Order_Quantity', 'Sales', 'Ship_Mode',
       'Profit', 'Customer_Name', 'Region', 'Customer_Segment',
       'Product_Category', 'Product_Sub-Category', 'Product_Name',
       'Product_Container'],
      dtype='object')

In [5]:
df.dtypes

Order_ID                  int64
Order_Priority           object
Order_Quantity            int64
Sales                   float64
Ship_Mode                object
Profit                  float64
Customer_Name            object
Region                   object
Customer_Segment         object
Product_Category         object
Product_Sub-Category     object
Product_Name             object
Product_Container        object
dtype: object

In [6]:
df.describe()

Order_ID  Order_Quantity         Sales       Profit
count    730.000000      730.000000    730.000000   730.000000
mean   29721.597260       24.857534   1502.777653   207.479233
std    17350.560439       14.182970   2893.936648   878.631028
min       35.000000        1.000000      8.600000 -4437.910000
25%    14479.000000       13.000000    171.098375   -77.132500
50%    29350.500000       25.000000    438.700000     0.035000
75%    44978.500000       37.000000   1480.855000   180.000000
max    59909.000000       50.000000  27663.920000  8417.570000

In [7]:
df.isnull().sum()

Order_ID                0
Order_Priority          0
Order_Quantity          0
Sales                   0
Ship_Mode               0
Profit                  0
Customer_Name           0
Region                  0
Customer_Segment        0
Product_Category        0
Product_Sub-Category    0
Product_Name            0
Product_Container       0
dtype: int64

In [8]:
len(df.columns)

13

In [9]:
len(df)

730

### Tratamento das colunas tipo string para tipo numérico: 
1. As colunas tipo string no dataset selecionado apresenta uma natureza categórica, ou seja, não-ordinária.
2. Desta forma, para cada coluna e seus respectivos valores, são criadas colunas artificiais com o valor "1" ou "0" .

In [10]:
np.unique(df['Order_Priority'], return_counts = True)
#Categórica_Nominal And Categórica_Ordinal

(array(['Critical', 'High', 'Low', 'Medium', 'Not Specified'], dtype=object),
 array([147, 152, 147, 128, 156]))

### Tratamento para a coluna 'Order_Priority'
1. Criado para cada valor categórico, é criado uma funcao e em seguida aplicado no dataset
2. Este tratamento é similar para as demais colunas

In [11]:
def order_pri_A(line):
    if line == 'Critical':
        return 1
    else:
        return 0

In [12]:
def order_pri_B(line):
    if line == 'High':
        return 1
    else:
        return 0

In [13]:
def order_pri_C(line):
    if line == 'Low':
        return 1
    else:
        return 0

In [14]:
def order_pri_D(line):
    if line == 'Medium':
        return 1
    else:
        return 0

In [15]:
def order_pri_E(line):
    if line == 'Not Specified':
        return 1
    else:
        return 0

In [16]:
df['Critical_Ship_Mode'] = df['Order_Priority'].apply(lambda x: order_pri_A(x))
df['High_Ship_Mode'] = df['Order_Priority'].apply(lambda x: order_pri_B(x))
df['Low_Ship_Mode'] = df['Order_Priority'].apply(lambda x: order_pri_C(x))
df['Medium_Ship_Mode'] = df['Order_Priority'].apply(lambda x: order_pri_D(x))
df['NotSfd_Ship_Mode'] = df['Order_Priority'].apply(lambda x: order_pri_E(x))

### Tratamento para a coluna 'Ship_Mode'

In [17]:
np.unique(df['Ship_Mode'], return_counts = True)

(array(['Express Air', 'Regular Air'], dtype=object), array([151, 579]))

In [18]:
def ship_m_R(line):
    if line == 'Regular Air':
        return 1
    else:
        return 0

In [19]:
def ship_m_E(line):
    if line == 'Express Air':
        return 1
    else: 
        return 0

In [20]:
df['Regular_Ship_Mode'] = df['Ship_Mode'].apply(lambda x: ship_m_R(x))

In [21]:
df['Express_Ship_Mode'] = df['Ship_Mode'].apply(lambda x: ship_m_E(x))

### Tratamento para as demais colunas

In [22]:
np.unique(df['Region'], return_counts = True)
#Categórica_Nominal

(array(['Atlantic', 'Northwest Territories', 'Nunavut', 'Ontario',
        'Prarie', 'West'], dtype=object),
 array([170, 150,  32,  67,  79, 232]))

In [23]:
def reg_F(line):
    if line == 'Atlantic':
        return 1
    else: 
        return 0

In [24]:
def reg_G(line):
    if line == 'Northwest Territories':
        return 1
    else: 
        return 0

In [25]:
def reg_H(line):
    if line == 'Nunavut':
        return 1
    else: 
        return 0

In [26]:
def reg_I(line):
    if line == 'Ontario':
        return 1
    else: 
        return 0

In [27]:
def reg_J(line):
    if line == 'Prarie':
        return 1
    else: 
        return 0

In [28]:
def reg_K(line):
    if line == 'West':
        return 1
    else: 
        return 0

In [29]:
df['Atlantic_Region'] = df['Region'].apply(lambda x: reg_F(x))
df['NT_Region']       = df['Region'].apply(lambda x: reg_G(x))
df['Nunavut_Region']  = df['Region'].apply(lambda x: reg_H(x))
df['Ontario_Region']  = df['Region'].apply(lambda x: reg_I(x))
df['Prarie_Region']   = df['Region'].apply(lambda x: reg_J(x))
df['West_Region']    = df['Region'].apply(lambda  x: reg_K(x))

In [30]:
np.unique(df['Customer_Segment'], return_counts = True)

(array(['Consumer', 'Corporate', 'Home Office', 'Small Business'],
       dtype=object),
 array([153, 518,  31,  28]))

In [31]:
def cs_L(line):
    if line == 'Consumer':
        return 1
    else: 
        return 0

In [32]:
def cs_M(line):
    if line == 'Corporate':
        return 1
    else: 
        return 0

In [33]:
def cs_N(line):
    if line == 'Home Office':
        return 1
    else: 
        return 0

In [34]:
def cs_O(line):
    if line == 'Small Business':
        return 1
    else: 
        return 0

In [35]:
df['Consumer_Customer_Segment'] = df['Customer_Segment'].apply(lambda x: cs_L(x))
df['Corporate_Customer_Segment'] = df['Customer_Segment'].apply(lambda x: cs_M(x))
df['HO_Customer_Segment'] = df['Customer_Segment'].apply(lambda x: cs_N(x))
df['SB_Customer_Segment'] = df['Customer_Segment'].apply(lambda x: cs_O(x))

In [36]:
np.unique(df['Product_Category'], return_counts = True)
#Categórica_Nominal

(array(['Furniture', 'Office Supplies', 'Technology'], dtype=object),
 array([ 98, 447, 185]))

In [37]:
def prod_R(line):
    if line == 'Furniture':
        return 1
    else: 
        return 0

In [38]:
def prod_S(line):
    if line == 'Office Supplies':
        return 1
    else: 
        return 0

In [39]:
def prod_T(line):
    if line == 'Technology':
        return 1
    else: 
        return 0

In [40]:
df['Furniture_Product_Category']  = df['Product_Category'].apply(lambda x: prod_R(x))
df['OF_Product_Category']         = df['Product_Category'].apply(lambda x: prod_S(x))
df['Technology_Product_Category'] = df['Product_Category'].apply(lambda x: prod_T(x))


In [41]:
np.unique(df['Product_Container'], return_counts = True)
#Categórica_Nominal

(array(['Large Box', 'Medium Box', 'Small Box'], dtype=object),
 array([ 63,  61, 606]))

In [42]:
def pc_U(line):
    if line == 'Large Box':
        return 1
    else: 
        return 0

In [43]:
def pc_V(line):
    if line == 'Medium Box':
        return 1
    else: 
        return 0

In [44]:
def pc_X(line):
    if line == 'Small Box':
        return 1
    else: 
        return 0

In [45]:
df['LB_Product_Container'] = df['Product_Container'].apply(lambda x: pc_U(x))
df['MB_Product_Container'] = df['Product_Container'].apply(lambda x: pc_V(x))
df['SB_Product_Container'] = df['Product_Container'].apply(lambda x: pc_X(x))


In [46]:
df.columns

Index(['Order_ID', 'Order_Priority', 'Order_Quantity', 'Sales', 'Ship_Mode',
       'Profit', 'Customer_Name', 'Region', 'Customer_Segment',
       'Product_Category', 'Product_Sub-Category', 'Product_Name',
       'Product_Container', 'Critical_Ship_Mode', 'High_Ship_Mode',
       'Low_Ship_Mode', 'Medium_Ship_Mode', 'NotSfd_Ship_Mode',
       'Regular_Ship_Mode', 'Express_Ship_Mode', 'Atlantic_Region',
       'NT_Region', 'Nunavut_Region', 'Ontario_Region', 'Prarie_Region',
       'West_Region', 'Consumer_Customer_Segment',
       'Corporate_Customer_Segment', 'HO_Customer_Segment',
       'SB_Customer_Segment', 'Furniture_Product_Category',
       'OF_Product_Category', 'Technology_Product_Category',
       'LB_Product_Container', 'MB_Product_Container', 'SB_Product_Container'],
      dtype='object')

### Finalização da preparação do dataframe
1 - serão removidas as colunas nominais e a coluna 'Order_ID' pois a mesma representa o código da operação (não contribuindo para a fase de treinamento). O mesmo se aplica à coluna 'Customer_Name' e 'Product_Name' <br>
2 - colunas removidas: <br>
'Order_ID', 'Order_Priority', 'Ship_Mode', 'Customer_Name', 'Region', 'Customer_Segment',
       'Product_Category', 'Product_Sub-Category','Product_Name','Product_Container'


In [47]:
df_prepare = df[['Order_Quantity', 'Sales', 'Profit', 'Critical_Ship_Mode', 
                 'High_Ship_Mode', 'Low_Ship_Mode', 'Medium_Ship_Mode', 
                 'NotSfd_Ship_Mode', 'Regular_Ship_Mode', 'Express_Ship_Mode', 
                 'Atlantic_Region', 'NT_Region', 'Nunavut_Region', 'Ontario_Region', 
                 'Prarie_Region','West_Region', 'Consumer_Customer_Segment',
                 'Corporate_Customer_Segment', 'HO_Customer_Segment','SB_Customer_Segment', 
                 'Furniture_Product_Category','OF_Product_Category', 
                 'Technology_Product_Category','LB_Product_Container', 
                 'MB_Product_Container', 'SB_Product_Container']]

In [48]:
df_prepare.head()

Order_Quantity    Sales  Profit  Critical_Ship_Mode  High_Ship_Mode  \
0              21  2781.82 -695.26                   0               1   
1              35  3389.93  737.94                   0               1   
2               7  2039.56 -329.49                   0               0   
3               6   905.94   -4.19                   0               0   
4              24  1168.15 -743.96                   0               0   

   Low_Ship_Mode  Medium_Ship_Mode  NotSfd_Ship_Mode  Regular_Ship_Mode  \
0              0                 0                 0                  0   
1              0                 0                 0                  0   
2              0                 0                 1                  0   
3              1                 0                 0                  0   
4              0                 1                 0                  0   

   Express_Ship_Mode  ...  Consumer_Customer_Segment  \
0                  1  ...                          0   
1                  1  ...                          1   
2                  1  ...                          0   
3                  1  ...                          0   
4                  1  ...                          0   

   Corporate_Customer_Segment  HO_Customer_Segment  SB_Customer_Segment  \
0                           1                    0                    0   
1                           0                    0                    0   
2                           1                    0                    0   
3                           0                    1                    0   
4                           0                    0                    1   

   Furniture_Product_Category  OF_Product_Category  \
0                           0                    1   
1                           1                    0   
2                           0                    1   
3                           1                    0   
4                           0                    1   

   Technology_Product_Category  LB_Product_Container  MB_Product_Container  \
0                            0                     1                     0   
1                            0                     1                     0   
2                            0                     1                     0   
3                            0                     1                     0   
4                            0                     1                     0   

   SB_Product_Container  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  

[5 rows x 26 columns]

### Reordenação da preparação do dataframe

In [49]:
df_prepare = df[['Order_Quantity', 'Critical_Ship_Mode', 
                 'High_Ship_Mode', 'Low_Ship_Mode', 'Medium_Ship_Mode', 
                 'NotSfd_Ship_Mode', 'Regular_Ship_Mode', 'Express_Ship_Mode', 
                 'Atlantic_Region', 'NT_Region', 'Nunavut_Region', 'Ontario_Region', 
                 'Prarie_Region','West_Region', 'Consumer_Customer_Segment',
                 'Corporate_Customer_Segment', 'HO_Customer_Segment','SB_Customer_Segment', 
                 'Furniture_Product_Category','OF_Product_Category', 
                 'Technology_Product_Category','LB_Product_Container', 
                 'MB_Product_Container', 'SB_Product_Container',
                 'Sales', 'Profit']]

In [50]:
df_prepare.head()

Order_Quantity  Critical_Ship_Mode  High_Ship_Mode  Low_Ship_Mode  \
0              21                   0               1              0   
1              35                   0               1              0   
2               7                   0               0              0   
3               6                   0               0              1   
4              24                   0               0              0   

   Medium_Ship_Mode  NotSfd_Ship_Mode  Regular_Ship_Mode  Express_Ship_Mode  \
0                 0                 0                  0                  1   
1                 0                 0                  0                  1   
2                 0                 1                  0                  1   
3                 0                 0                  0                  1   
4                 1                 0                  0                  1   

   Atlantic_Region  NT_Region  ...  HO_Customer_Segment  SB_Customer_Segment  \
0                0          0  ...                    0                    0   
1                0          1  ...                    0                    0   
2                0          1  ...                    0                    0   
3                0          1  ...                    1                    0   
4                0          1  ...                    0                    1   

   Furniture_Product_Category  OF_Product_Category  \
0                           0                    1   
1                           1                    0   
2                           0                    1   
3                           1                    0   
4                           0                    1   

   Technology_Product_Category  LB_Product_Container  MB_Product_Container  \
0                            0                     1                     0   
1                            0                     1                     0   
2                            0                     1                     0   
3                            0                     1                     0   
4                            0                     1                     0   

   SB_Product_Container    Sales  Profit  
0                     0  2781.82 -695.26  
1                     0  3389.93  737.94  
2                     0  2039.56 -329.49  
3                     0   905.94   -4.19  
4                     0  1168.15 -743.96  

[5 rows x 26 columns]

### Gravação da dataframe finalizado nesta etapa

In [51]:
df_prepare.to_csv('data/dados_prep.csv', index=None)

In [52]:
df_p2 = df[['Order_ID','Order_Priority','Order_Quantity', 'Critical_Ship_Mode', 
                 'High_Ship_Mode', 'Low_Ship_Mode', 'Medium_Ship_Mode', 
                 'NotSfd_Ship_Mode', 'Regular_Ship_Mode', 'Express_Ship_Mode', 
                 'Atlantic_Region', 'NT_Region', 'Nunavut_Region', 'Ontario_Region', 
                 'Prarie_Region','West_Region', 'Consumer_Customer_Segment',
                 'Corporate_Customer_Segment', 'HO_Customer_Segment','SB_Customer_Segment', 
                 'Furniture_Product_Category','OF_Product_Category', 
                 'Technology_Product_Category','LB_Product_Container', 
                 'MB_Product_Container', 'SB_Product_Container', 'Sales', 'Profit']]

In [53]:
df_p2.to_csv('data/dados_prep_index.csv', index=None)