In [1]:
import pandas as pd

In [37]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import plotly.express as px
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
import pickle
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification
from sklearn import svm
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier

from sklearn.model_selection import cross_val_score

In [3]:
df = pd.read_csv("data/dados.csv")

In [4]:
df.head()

Order_ID Order_Priority  Order_Quantity    Sales    Ship_Mode  Profit  \
0       643           High              21  2781.82  Express Air -695.26   
1      8995           High              35  3389.93  Express Air  737.94   
2      9127  Not Specified               7  2039.56  Express Air -329.49   
3     26272            Low               6   905.94  Express Air   -4.19   
4     36646         Medium              24  1168.15  Express Air -743.96   

        Customer_Name                 Region Customer_Segment  \
0      Monica Federle                Nunavut        Corporate   
1          Beth Paige  Northwest Territories         Consumer   
2         Bryan Davis  Northwest Territories        Corporate   
3         Carlos Daly  Northwest Territories      Home Office   
4  Muhammed MacIntyre  Northwest Territories   Small Business   

  Product_Category    Product_Sub-Category  \
0  Office Supplies  Storage & Organization   
1        Furniture      Office Furnishings   
2  Office Supplies  Storage & Organization   
3        Furniture      Chairs & Chairmats   
4  Office Supplies  Storage & Organization   

                                        Product_Name Product_Container  
0              SAFCO Commercial Wire Shelving, Black         Large Box  
1       Luxo Professional Combination Clamp-On Lamps         Large Box  
2  Tennsco Snap-Together Open Shelving Units, Sta...         Large Box  
3                           Hon Olson Stacker Stools         Large Box  
4                        Tennsco Industrial Shelving         Large Box

In [11]:
len(list(df.columns))

13

In [6]:
list(df.columns)

['Order_ID',
 'Order_Priority',
 'Order_Quantity',
 'Sales',
 'Ship_Mode',
 'Profit',
 'Customer_Name',
 'Region',
 'Customer_Segment',
 'Product_Category',
 'Product_Sub-Category',
 'Product_Name',
 'Product_Container']

In [7]:
df.dtypes

Order_ID                  int64
Order_Priority           object
Order_Quantity            int64
Sales                   float64
Ship_Mode                object
Profit                  float64
Customer_Name            object
Region                   object
Customer_Segment         object
Product_Category         object
Product_Sub-Category     object
Product_Name             object
Product_Container        object
dtype: object

In [13]:
cols = ['Order_Priority', 'Order_Quantity','Sales','Customer_Segment','Profit']

In [8]:
df.describe()

Order_ID  Order_Quantity         Sales       Profit
count    730.000000      730.000000    730.000000   730.000000
mean   29721.597260       24.857534   1502.777653   207.479233
std    17350.560439       14.182970   2893.936648   878.631028
min       35.000000        1.000000      8.600000 -4437.910000
25%    14479.000000       13.000000    171.098375   -77.132500
50%    29350.500000       25.000000    438.700000     0.035000
75%    44978.500000       37.000000   1480.855000   180.000000
max    59909.000000       50.000000  27663.920000  8417.570000

In [15]:
df[['Order_Priority', 'Order_Quantity','Sales','Customer_Segment','Profit']]

Order_Priority  Order_Quantity    Sales Customer_Segment   Profit
0             High              21  2781.82        Corporate  -695.26
1             High              35  3389.93         Consumer   737.94
2    Not Specified               7  2039.56        Corporate  -329.49
3              Low               6   905.94      Home Office    -4.19
4           Medium              24  1168.15   Small Business  -743.96
..             ...             ...      ...              ...      ...
725  Not Specified              44  5347.13        Corporate  1886.41
726       Critical              22   127.33        Corporate     5.30
727       Critical              24   990.10        Corporate   310.22
728  Not Specified               5    28.32        Corporate   -14.35
729         Medium              39   796.08        Corporate    30.29

[730 rows x 5 columns]

In [19]:
def lucro(valor):
    if valor > 0:
        return 1
    else:
        return 0

In [20]:
df['Target'] = df['Profit'].apply(lambda x: lucro(x))

In [22]:
df[['Order_Priority', 'Order_Quantity','Sales','Customer_Segment','Target']]

Order_Priority  Order_Quantity    Sales Customer_Segment  Target
0             High              21  2781.82        Corporate       0
1             High              35  3389.93         Consumer       1
2    Not Specified               7  2039.56        Corporate       0
3              Low               6   905.94      Home Office       0
4           Medium              24  1168.15   Small Business       0
..             ...             ...      ...              ...     ...
725  Not Specified              44  5347.13        Corporate       1
726       Critical              22   127.33        Corporate       1
727       Critical              24   990.10        Corporate       1
728  Not Specified               5    28.32        Corporate       0
729         Medium              39   796.08        Corporate       1

[730 rows x 5 columns]

In [24]:
import numpy as np
np.unique(df['Order_Priority'], return_counts = True)

(array(['Critical', 'High', 'Low', 'Medium', 'Not Specified'], dtype=object),
 array([147, 152, 147, 128, 156]))

In [25]:
import numpy as np
np.unique(df['Customer_Segment'], return_counts = True)

(array(['Consumer', 'Corporate', 'Home Office', 'Small Business'],
       dtype=object),
 array([153, 518,  31,  28]))

In [31]:
c_Order_Priority('Critical')

In [32]:
def c_Order_Priority(line):
    if line =='Critical' :
        return 1
    else:
        return 0
def h_Order_Priority(line):
    if line =='High' :
        return 1
    else:
        return 0
def l_Order_Priority(line):
    if line =='Low' :
        return 1
    else:
        return 0
        
def m_Order_Priority(line):
    if line =='Medium' :
        return 1
    else:
        return 0
def n_Order_Priority(line):
    if line =='Not Specified' :
        return 1
    else:
        return 0

In [33]:
df['c_Order_Priority'] = df['Order_Priority'].apply(lambda x: c_Order_Priority(x))
df['h_Order_Priority'] = df['Order_Priority'].apply(lambda x: h_Order_Priority(x))
df['l_Order_Priority'] = df['Order_Priority'].apply(lambda x: l_Order_Priority(x))
df['m_Order_Priority'] = df['Order_Priority'].apply(lambda x: m_Order_Priority(x))
df['n_Order_Priority'] = df['Order_Priority'].apply(lambda x: n_Order_Priority(x))

In [35]:
dfx = df[['c_Order_Priority','h_Order_Priority', 'l_Order_Priority', 
    'm_Order_Priority', 'n_Order_Priority', 'Order_Quantity','Sales','Target']]

In [38]:
dfx.dtypes

c_Order_Priority      int64
h_Order_Priority      int64
l_Order_Priority      int64
m_Order_Priority      int64
n_Order_Priority      int64
Order_Quantity        int64
Sales               float64
Target                int64
dtype: object

In [46]:
import numpy as np
np.unique(df['Target'], return_counts = True)

(array([0, 1]), array([365, 365]))

In [51]:
((2*365)*20)/100

146.0

In [52]:
77 + 69

146

In [39]:
X =  dfx.drop(['Target'], axis = 1)
Y =  df['Target']

In [40]:
seed = 1234
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size = 0.2, random_state = seed )

In [41]:
KNN_model = KNeighborsClassifier(n_neighbors=5)

In [42]:
KNN_model.fit(X_train, y_train)
KNN_prediction = KNN_model.predict(X_test)

In [43]:
KNN_model.fit(X_train, y_train)
KNN_prediction = KNN_model.predict(X_test)

In [44]:
print(accuracy_score(KNN_prediction, y_test))

0.726027397260274


In [45]:
print(classification_report(KNN_prediction, y_test))

              precision    recall  f1-score   support

           0       0.79      0.65      0.71        77
           1       0.67      0.81      0.74        69

    accuracy                           0.73       146
   macro avg       0.73      0.73      0.73       146
weighted avg       0.74      0.73      0.72       146



In [53]:
models = []

models.append(("LogisticRegression",LogisticRegression()))
models.append(("SVC",SVC()))
models.append(("LinearSVC",LinearSVC()))
models.append(("KNeighbors",KNeighborsClassifier()))
models.append(("DecisionTree",DecisionTreeClassifier()))
models.append(("RandomForest",RandomForestClassifier()))
rf2 = RandomForestClassifier(n_estimators=100, criterion='gini',
                                max_depth=10, random_state=0, max_features=None)
models.append(("RandomForest2",rf2))
models.append(("MLPClassifier",MLPClassifier(solver='lbfgs', random_state=0)))


results = []
names = []
for name,model in models:
    result = cross_val_score(model, X,Y,  cv=3)
    names.append(name)
    results.append(result)

for i in range(len(names)):
    print(names[i],results[i].mean())

/home/mardoniofranca/work/env/lib/python3.10/site-packages/sklearn/svm/_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/mardoniofranca/work/env/lib/python3.10/site-packages/sklearn/svm/_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/mardoniofranca/work/env/lib/python3.10/site-packages/sklearn/svm/_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/mardoniofranca/work/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
/home/ma

LogisticRegression 0.6314342575726911
SVC 0.7069025613348625
LinearSVC 0.5260631001371743
KNeighbors 0.6863545391171377
DecisionTree 0.6219163911938653
RandomForest 0.7082461939778272
RandomForest2 0.7178540106591109
MLPClassifier 0.7219411275270412


/home/mardoniofranca/work/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


In [9]:
df.isnull().sum()

Order_ID                0
Order_Priority          0
Order_Quantity          0
Sales                   0
Ship_Mode               0
Profit                  0
Customer_Name           0
Region                  0
Customer_Segment        0
Product_Category        0
Product_Sub-Category    0
Product_Name            0
Product_Container       0
dtype: int64

In [10]:
df.shape

(730, 13)